[build]
  publish = "_site"
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

# Redirect root domains to correct homepages
[[redirects]]
  from = "https://aaact.canada.ca/"
  to = "https://aaact.canada.ca/home"
  status = 301
  force = true

[[redirects]]
  from = "https://aatia.canada.ca/"
  to = "https://aatia.canada.ca/accueil"
  status = 301
  force = true

# Redirect old localized URLs to their new non-locale versions
[[redirects]]
  from = "/en/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/fr/*"
  to = "/:splat"
  status = 301
  force = true

# Redirect all French pages to `aatia.canada.ca`
[[redirects]]
  from = "https://aaact.canada.ca/fr/*"
  to = "https://aatia.canada.ca/fr/:splat"
  status = 301
  force = true


	# Opt-in to the Netlify Lighthouse plugin (choose one):

	# 1. Go to your site on https://app.netlify.com and navigate to the Integrations tab, search for the `Lighthouse` plugin
	# 2. Or via `npm install -D @netlify/plugin-lighthouse`

	# Read more: https://github.com/netlify/netlify-plugin-lighthouse

	# package = "@netlify/plugin-lighthouse"

	# # optional, fails build when a category is below a threshold
	# [plugins.inputs.thresholds]
	# 	performance = 1.0
	# 	accessibility = 1.0
	# 	best-practices = 1.0
	# 	seo = 1.0

	# [plugins.inputs]
	# 	output_path = "reports/lighthouse/index.html"
